version: '3.5'

services:
    database:
        image: 'postgres:13-alpine'
        environment:
            - POSTGRES_PASSWORD=main
            - POSTGRES_USER=main
            - POSTGRES_DB=main
        ports:
            - "5432:5432"
